
cc_library(
    name = "lines",
    srcs = ["lines.h", "lines.cc"],
    copts = ["-std=c++17"],
)

cc_binary(
    name = "part-1",
    srcs = ["part-1.cc"],
    deps = ["lines"],
    copts = ["-std=c++17"],
)
